"""empty message

Revision ID: 3b1c4ed6f4ab
Revises: f9c68f82a77a
Create Date: 2022-07-29 17:41:44.875488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b1c4ed6f4ab'
down_revision = 'f9c68f82a77a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_profile_id', table_name='user_profile')
    op.drop_table('user_profile')
    op.drop_index('ix_official_information_id', table_name='official_information')
    op.drop_table('official_information')
    op.drop_index('ix_personal_info_id', table_name='personal_info')
    op.drop_table('personal_info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_info',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('blood_group', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('marital_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('emergency_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('current_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('permanent_address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='personal_info_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='personal_info_pkey')
    )
    op.create_index('ix_personal_info_id', 'personal_info', ['id'], unique=False)
    op.create_table('official_information',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('join_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('experience', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('skype_id', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('gitlab_id', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('github_id', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='official_information_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='official_information_pkey')
    )
    op.create_index('ix_official_information_id', 'official_information', ['id'], unique=False)
    op.create_table('user_profile',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('profile_image', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('birthday', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_profile_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_profile_pkey')
    )
    op.create_index('ix_user_profile_id', 'user_profile', ['id'], unique=False)
    # ### end Alembic commands ###
