"""empty message

Revision ID: 6b64c647d1cd
Revises: 1f5c0971b0ab
Create Date: 2022-08-17 13:39:40.173635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b64c647d1cd'
down_revision = '1f5c0971b0ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eod',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dept_user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time_stamp', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['dept_user_id'], ['department_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eod_date'), 'eod', ['date'], unique=False)
    op.create_index(op.f('ix_eod_id'), 'eod', ['id'], unique=False)
    op.create_table('sod',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dept_user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['dept_user_id'], ['department_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sod_date'), 'sod', ['date'], unique=False)
    op.create_index(op.f('ix_sod_id'), 'sod', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sod_id'), table_name='sod')
    op.drop_index(op.f('ix_sod_date'), table_name='sod')
    op.drop_table('sod')
    op.drop_index(op.f('ix_eod_id'), table_name='eod')
    op.drop_index(op.f('ix_eod_date'), table_name='eod')
    op.drop_table('eod')
    # ### end Alembic commands ###
