"""empty message

Revision ID: 7cff4d22df3d
Revises: 37386630896d
Create Date: 2022-07-25 16:54:43.772582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cff4d22df3d'
down_revision = '37386630896d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('personal_info', 'current_address',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('personal_info', 'permanent_address',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('personal_info', 'permanent_address',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('personal_info', 'current_address',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
