"""empty message

Revision ID: c870b8da0719
Revises: 7cff4d22df3d
Create Date: 2022-07-25 16:56:27.287539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c870b8da0719'
down_revision = '7cff4d22df3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'address',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'address',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
