"""empty message

Revision ID: d89d302efb64
Revises: 81ec6e8be93b
Create Date: 2022-08-01 11:59:41.370399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd89d302efb64'
down_revision = '81ec6e8be93b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('department_user_user_role_id_fkey', 'department_user', type_='foreignkey')
    op.create_foreign_key(None, 'department_user', 'user_role', ['user_role_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'department_user', type_='foreignkey')
    op.create_foreign_key('department_user_user_role_id_fkey', 'department_user', 'role', ['user_role_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
